LDLIBS	= -lraptor2 -lpcre
CFLAGS	= -fblocks -g -pedantic -Wall -I../src -I/usr/local/include/raptor2 -I/usr/include/raptor2
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	LDLIBS += -lBlocksRuntime
endif
ifeq ($(UNAME_S),Darwin)
	CFLAGS += -std=c11
endif

CC		= clang

%.o: %.h %.c

ts: ts.c triplestore.o avl.o linenoise.o
	$(CC) $(LDLIBS) $(CFLAGS) -o ts ts.c triplestore.o avl.o linenoise.o

clean:
	rm -f ts
	rm -f avl.o linenoise.o triplestore.o
	rm -rf *.dSYM

.PHONY	: clean
